---
title: "Cell seg data summary"
date: "`r Sys.Date()`"
output: 
  html_vignette:
    df_print: kable
params:
  csd_path: 
    label: "Path to cell seg data file:"
    value: NULL
    input: file
  csd: NULL
  dataset_name: NULL
---

```{r setup, echo=FALSE,include=FALSE,message=FALSE}
knitr::opts_chunk$set(echo=FALSE,fig.width=9, fig.height=6, 
                      comment=NA, warning=FALSE, message=FALSE)

library(tidyverse)
library(phenoptr)
```

<style type="text/css">
table {
    width: auto !important;
    max-width: 100%;
    margin-bottom: 20px;
    margin-left: 0px;
}
</style>

```{r}
if (is.null(params$csd_path) == is.null(params$csd))
  stop('csd_path or csd must be provided but not both.')

csd = if (!is.null(params$csd)) params$csd else read_cell_seg_data(params$csd_path)

# If csd_path was provided, look for a companion 'rejected' file
rejected = NULL
if (!is.null(csd_path) && str_detect(csd_path, 'cell_seg_data.txt')) {
  # Try summary first
  rejected_path = str_replace(csd_path, 'cell_seg_data',
                              'rejected_cell_seg_data_summary')
  if (!file.exists(rejected_path))
    rejected_path = str_replace(csd_path, 'cell_seg_data',
                              'rejected_cell_seg_data')
  if(file.exists(rejected_path)) {
    rejected = read_cell_seg_data(rejected_path)
    
    # Don't report on empty rejected file
    if (nrow(rejected) == 0)
      rejected = NULL
  }
}
```

```{r results='asis'}
if (!is.null(params$dataset_name)) {
  cat('Summary of cell seg data for **', params$dataset_name, '**.\n\n', sep='')
} else if (!is.null(params$csd_path)) {
  cat('Summary of cell seg data from  \n`', params$csd_path, '`.\n\n')
}
```


## Slides and fields

This file contains data on `r n_distinct(csd[['Sample Name']])` fields 
taken from `r n_distinct(csd[['Slide ID']])` slides:

```{r}
csd %>% group_by(`Slide ID`) %>% 
  summarize(`Number of fields`=n_distinct(`Sample Name`))
```

```{r results='asis'}
if (!is.null(rejected)) {
  cat('\n\n### Rejected fields\n\n')
  cat(n_distinct(rejected[['Sample Name']]), 
      ' fields from ', n_distinct(rejected[['Slide ID']]), 
      ' slides were rejected in the merge step:\n\n', sep='')
  
  rejected %>% group_by(`Slide ID`) %>% 
    summarize(`Number of fields`=n_distinct(`Sample Name`))
}
```

## Tissue categories

The tissue categories present are

```{r results='asis'}
cats = unique(csd$`Tissue Category`)
cat('\n- ', paste(cats, collapse='\n- '), '\n\n', sep='')
```

## Phenotypes

The phenotypes present, and their total counts, are

```{r}
if ('Phenotype' %in% names(csd)) {
  # Old-style phenotypes (single column)
  counts = csd %>% count(Phenotype) %>% 
    rename(Count='n') %>% 
    mutate(Phenotype=ifelse(Phenotype=='', 'N/A', Phenotype))
} else {
  # Phenotype per marker
  counts = csd %>% select(starts_with('Phenotype')) %>% 
    gather() %>% 
    filter(!str_detect(value, '-$')) %>% 
    count(value) %>% 
    rename(Phenotype='value', Count='n') %>% 
    mutate(Phenotype=ifelse(Phenotype=='', 'N/A', Phenotype))
}

total = sum(counts$Count)
counts %>% spread(Phenotype, Count) %>% 
  mutate(`Total Cells`=total)
```

### Phenotype counts per slide

```{r}
if ('Phenotype' %in% names(csd)) {
  # Old-style phenotypes (single column)
  counts = csd %>% count(`Slide ID`, `Phenotype`) %>% 
    mutate(Phenotype=ifelse(Phenotype=='', 'N/A', Phenotype)) %>% 
    rename(Count='n')
} else {
  # Phenotype per marker
  counts = csd %>% select(`Slide ID`, starts_with('Phenotype')) %>% 
    gather('key', 'value', -`Slide ID`) %>% 
    filter(!str_detect(value, '-$')) %>% 
    group_by(`Slide ID`) %>% 
    count(value) %>% 
    rename(Phenotype='value', Count='n') %>%
    mutate(Phenotype=ifelse(Phenotype=='', 'N/A', Phenotype))
}

  totals = counts %>% dplyr::group_by(`Slide ID`) %>%
    dplyr::summarize(`Total Cells` = sum(Count))
  counts %>% spread(Phenotype, Count, fill=0) %>% left_join(totals)

```

```{r results='asis'}
# For phenotype per marker we can show UpSet plots. For classic phenotyping
# they don't add much to the tabular summaries.
if (!'Phenotype' %in% names(csd) && require(UpSetR)) {
  # Some explanation
  cat('\n\n### UpSet plots of phenotype combinations\n\n')
  cat('These "UpSet" plots visualize combinations of phenotypes.
      The horizontal bars show counts of the individual phenotypes.
      The vertical bars show counts of the combination phenotypes
      present in the data. The central matrix shows the combinations
      graphically.')
  
  # UpSet plot for the whole dataset
  cat('\n\n#### Phenotype combinations, all data\n\n')
  print(upset_plot(csd))
  
  # And for each slide
  for (slide in unique(csd$`Slide ID`)) {
    cat('\n\n#### Phenotype combinations, ', slide, '\n\n', sep='')
    print(upset_plot(csd %>% filter(`Slide ID`==slide)))
  }
}
```

