---
title: "Signal to Noise Measurements"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
params:
  export_path: 
    label: "Path to directory with component data"
    value: F:\Opal\180926 9color\181010 9 color libraries for Kent\Export new bands
    input: file
---

<style type="text/css">
table {
    width: auto !important;
    max-width: 100%;
    margin-bottom: 20px;
    margin-left: 0px;
}

.fill-cell>tbody>tr>td {
  padding: 0px;
  border-color: black;
  border: 1px solid;
}

.fill-cell>thead>tr>th {
  border-color: black;
  border: 1px solid;
}
</style>

```{r setup, echo=FALSE,include=FALSE,message=FALSE}
knitr::opts_chunk$set(echo=FALSE,fig.width=9, fig.height=6, 
                      comment=NA, warning=FALSE, message=FALSE)

library(tidyverse)
library(phenoptr)
```

Signal-to-noise measurements  on singly-stained samples
from <pre>`r params$export_path`</pre>.

```{r functions}
process_file = function(path, primary_fluor, percentile=NULL) {
  # Progress output
  message('Processing fluor ', primary_fluor, ' from ', path)
  
  # Read the components and get the primary one
  comps = read_components(path)

  if (!primary_fluor %in% names(comps))
    stop('Primary fluor ', primary_fluor, ' not found in component data file"', path, '"')

  primary = comps[[primary_fluor]]

  # Find the top-expressing `percentile` pixels
  if (is.null(percentile)) {
    # Find the top-expressing 3200 pixels, approximately.
    # The magic number is from Carla
    percentile = 1-3200/prod(dim(primary))
  }

  cutoff = quantile(primary, percentile)
  mask = primary >= cutoff

  signals = purrr::map_dfc(comps, ~ dplyr::tibble(Mean=mean(.x[mask]))) %>%
    purrr::set_names(names(comps))

  sn = signals / signals[[primary_fluor]]

  signals$Primary = sn$Primary = primary_fluor
  signals$Source = sn$Source = basename(path)

  list(signals=signals, sn=sn)
}

```

```{r data}
comp_files = list.files(params$export_path, pattern='component_data.tif', full.names=TRUE)

# Put DAPI first
dapi_files = stringr::str_detect(comp_files, 'DAPI')
comp_files = c(comp_files[dapi_files], comp_files[!dapi_files])
crosstalk = purrr::map_dfr(comp_files, function(path) {
  process_file(path, phenoptrReports:::file_to_fluor(path))$sn
})

crosstalk = crosstalk %>%
  dplyr::select(Primary, Source, DAPI, dplyr::everything())
```

```{r format}
library(formattable)

message('Creating report')

to_display = crosstalk %>% 
  dplyr::select(-Primary, -Autofluorescence) %>% 
  dplyr::mutate_at(-1, percent, digits=1)

# Put columns in alpha order with DAPI first
to_display = to_display[sort(names(to_display))] %>% 
  dplyr::select(Source, dplyr::matches('DAPI'), dplyr::everything())

my_gradient = function(colors) {
  grad = colorRamp(colors, space='Lab')
  function(x) {
    color = grad(x)
    colnames(color)= c('red', 'green', 'blue')
    formattable::csscolor(round(t(color), 0), format='rgb')
  }
}

# Overall maximum
limit = max({x<-unlist(to_display[,-1]); x[x<1]})

# Colors for the green-yellow-red/orange ramp
# Excel colors from Carla
# green = '#00B050'
# yellow = '#FFEB84'
# red_orange = '#ED7D31'

# These are a bit more saturated
green = '#08b151'
yellow = 'gold'
red_orange = 'red'

my_color = function(x) {
  cutpt = 0.015
  green_ramp = my_gradient(c(green, yellow))
  yellow_ramp = my_gradient(c(yellow, red_orange))
  ifelse(x==1, csscolor('white'), # Don't show 100%
         ifelse(x<=cutpt, green_ramp(x/cutpt),
                yellow_ramp((x-cutpt)/(limit-cutpt))))
}

my_font_weight= function(x) ifelse(x>0.005 & x<1, 'bold', 'normal')

# Make a color_tile variation
my_color_tile = function (...) 
{
    formattable::formatter("span", 
                           style = function(x) 
                             formattable::style(display = "block", 
        padding = "3px", `border-radius` = "0px",
        `background-color` = my_color(x), 
        color = ifelse(x==1, 'white', 'black'),
        `font-weight`=my_font_weight(x)))
}

padded_cell = function (...) 
{
    formattable::formatter("span", 
                           style = function(x) 
                             formattable::style(display = "block", 
        padding = "3px"))
}

formats = purrr::map(names(to_display)[-1], my_color_tile) %>% 
  purrr::set_names(names(to_display)[-1]) %>% 
  c(list(Source=padded_cell('Source')))

formattable::formattable(to_display, formats, 
                         align=c('l', rep('r', ncol(to_display)-1)),
            table.attr = "class=\"table table-condensed fill-cell\"")
```

